name: Windows ARM64 CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  tests:
    name: ARM64 (${{ matrix.channel }})
    runs-on: windows-11-arm
    strategy:
      fail-fast: false
      matrix:
        channel: [stable, '1.95.0']
    defaults:
      run:
        shell: pwsh
    env:
      RUST_BACKTRACE: full
      RUSTUP_TOOLCHAIN: ${{ matrix.channel }}-aarch64-pc-windows-msvc
      CARGO_BUILD_TARGET: aarch64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - name: Install native ARM64 Rust toolchain
        run: rustup toolchain install $env:RUSTUP_TOOLCHAIN --profile minimal
      - name: Create Cargo.lock
        run: cargo generate-lockfile
      - name: Run tests (no features)
        run: cargo test --locked --release --no-fail-fast --no-default-features
      - name: Run tests (all features)
        run: cargo test --locked --release --no-fail-fast --all-features
